"""Add date_seen column

Revision ID: 39d49e14ad71
Revises: a073a02976b2
Create Date: 2025-05-21 02:00:52.467054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d49e14ad71'
down_revision = 'a073a02976b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_seen', sa.String(length=120), nullable=True))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_seen', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('date_seen')

    with op.batch_alter_table('inventory_tag', schema=None) as batch_op:
        batch_op.drop_column('date_seen')

    # ### end Alembic commands ###
