"""Add InventoryTag model

Revision ID: a073a02976b2
Revises: f85a8e77247a
Create Date: 2025-05-14 16:34:29.899465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a073a02976b2'
down_revision = 'f85a8e77247a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('last_seen', sa.String(length=120), nullable=False),
    sa.Column('time_seen', sa.String(length=120), nullable=False),
    sa.Column('last_changed_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rfid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_tag')
    # ### end Alembic commands ###
